from .table_widget import TableWidget
from .annotate_precise_widget import AnnotatePreciseWidget
from .annotate_buttons_widget import AnnotateButtonsWidget
from .player_controls import PlayerControls
from .annotation_statistics_widget import AnnotationsStatisticsWindow
from .labels_file_widget import LabelsFileWindow
from .import_widget import ImportWindow